# Generated by Django 5.0.4 on 2026-05-07 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticstracking',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='orders.order'),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='tracking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='logistics.logisticstracking'),
        ),
    ]
